import type { NextPage } from 'next'
import Head from 'next/head'

import Hero from '@/atomic/organisms/Hero'
import HorizontalProducts from '@/atomic/organisms/horizontalProducts'
import HeaderMenu from '@/components/HeaderMenu'
import TrustBox from '@/components/TrustBox'
import { getShopPageForHome } from '@/lib/api'
import { getTrustpilotReviews } from '@/lib/trustpilot'

const Home: NextPage = ({ shop, products, reviews }: any) => {
  console.log('shop', shop)
  console.log('products', products)
  console.log('reviews', reviews)
  return (
    <div>
      <Head>
        <title>{shop.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon/favicon.ico" />
      </Head>

      <HeaderMenu reviews={reviews} />

      <main>
        <Hero />
        <HorizontalProducts />
      </main>

      {/* <footer>Footer</footer> */}
    </div>
  )
}

export async function getStaticProps() {
  const data = await getShopPageForHome()
  const reviews = await getTrustpilotReviews()
  return { props: { ...data, reviews } }
}

export default Home
