import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '@/atomic/organisms/Header'
import TrustBox from '@/components/TrustBox'
import { getShopPageForHome } from '@/lib/api'
import getTrustpilotReviews from '@/lib/trustpilot'

const Home: NextPage = ({ shop, products, reviews }: any) => {
  console.log('shop', shop)
  console.log('products', products)
  return (
    <div>
      <Head>
        <title>{shop.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon/favicon.ico" />
      </Head>

      <TrustBox nbReviews={reviews.nbReviews} rating={reviews.rating} />
      <Header />
      {/*
      <main>
        <h1 className="text-3xl font-bold text-blue-500 underline">Hello {shop.name} !</h1>
        <Button />
      </main>

      <footer>Footer</footer> */}
    </div>
  )
}

export async function getStaticProps() {
  const data = await getShopPageForHome()
  const reviews = await getTrustpilotReviews()
  return { props: { ...data, reviews } }
}

export default Home
