import { QueryClient, dehydrate } from '@tanstack/react-query'
import algoliasearch from 'algoliasearch/lite'
import type { GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import { renderToString } from 'react-dom/server'
import { getServerState } from 'react-instantsearch-hooks-server'
import { Configure, InstantSearch, InstantSearchSSRProvider } from 'react-instantsearch-hooks-web'

import Layout from '@/components/Layout'
import ProductsComponent from '@/components/Products'
import { routing } from '@/lib/betterUrl'
import getShopPageForProducts from '@/lib/getShopPageForProducts'
import { getTrustpilotReviews } from '@/lib/trustpilot'

const APP_ID = process.env.NEXT_PUBLIC_ALGOLIA_APP_ID || ''
const API_KEY = process.env.NEXT_PUBLIC_ALGOLIA_API_KEY || ''
const INDEX_NAME = process.env.NEXT_PUBLIC_ALGOLIA_INDEX_NAME || ''

const searchClient = algoliasearch(APP_ID, API_KEY)

export default function Products(props: any) {
  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout crumb={[{ title: 'Accueil', route: '/' }, { title: 'Produits' }]}>
        <ProductsBody {...props} />
      </Layout>
    </>
  )
}

export function ProductsBody({ serverState, url }: any) {
  return (
    <InstantSearchSSRProvider {...serverState}>
      <InstantSearch searchClient={searchClient} indexName={INDEX_NAME} routing={routing(url)}>
        <Configure hitsPerPage={20} />
        <ProductsComponent />
      </InstantSearch>
    </InstantSearchSSRProvider>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { req } = context
  const protocol = req.headers.referer?.split('://')[0] || 'https'
  const url = `${protocol}://${req.headers.host}${req.url}`

  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(['shopProducts'], getShopPageForProducts)
  await queryClient.prefetchQuery(['reviews'], getTrustpilotReviews)
  const dehydratedState = dehydrate(queryClient)

  const serverState = await getServerState(<ProductsBody url={url} />, { renderToString })
  return {
    props: {
      dehydratedState,
      serverState,
      url,
    },
  }
}
